site_name: Botler
site_description: Wiki for everything about Botler, a general purpose Discord bot
repo_url: https://github.com/Botler-Dev/Botler

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    repo: fontawesome/brands/github

plugins:
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - search

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AQBYTSxg4C
    - icon: fontawesome/brands/github
      link: https://github.com/Botler-Dev/Botler

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - footnotes
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - toc:
      permalink: true

nav:
  - Home:
      - Introduction: index.md
      - License: License.md
  - Development:
      - Database Schema: Development/Database-Schema.md
