apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storageclass
  namespace: botler
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-0
  namespace: botler
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storageclass
  capacity:
    storage: 100Mi
  claimRef:
    namespace: botler
    name: data-botler-postgresql-postgresql-ha-postgresql-0
  local:
    path: /data/postgres_volume_0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [ intel01 ]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-1
  namespace: botler
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storageclass
  capacity:
    storage: 100Mi
  claimRef:
    namespace: botler
    name: data-botler-postgresql-postgresql-ha-postgresql-1
  local:
    path: /data/postgres_volume_1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [ intel01 ]

