apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storageclass
  namespace: botler
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-master
  namespace: botler
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: postgres-storageclass
  capacity:
    storage: 100Mi
  claimRef:
    namespace: botler
    name: data-botler-postgresql-postgresql-master-0
  local:
    path: /data/postgres_volume_master
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [ intel01 ]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-slave
  namespace: botler
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: postgres-storageclass
  capacity:
    storage: 100Mi
  claimRef:
    namespace: botler
    name: data-botler-postgresql-slave-0
  local:
    path: /data/postgres_volume_slave
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [ intel01 ]
