version: 2.1
jobs:
  build:
    docker:
      - image: node:14-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Add Bot Config
          command: |
            echo "{\"ormconfig\": {}}" > src/botconfig.json
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - run:
          name: Build Bot
          command: |
            npm run build:prod
  eslint:
    docker:
      - image: node:14-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Run linter
          command: |
            npm run lint
workflow:
  default:
    jobs:
      - build
      - eslint:
          requires:
            - build
