version: 2.1
executors:
  node-executor:
    docker:
      - image: node:15-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
commands:
  setup-project:
    description: 'Checks out, installs the dependencies and adds a bot config'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
jobs:
  build:
    executor: node-executor
    steps:
      - setup-project
      - run:
          name: Build Bot
          command: |
            yarn build:prod
  eslint:
    executor: node-executor
    steps:
      - setup-project
      - run:
          name: Run linter
          command: |
            yarn lint
workflows:
  default:
    jobs:
      - build
      - eslint
