FROM node:15-alpine

WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

COPY tsconfig.json ./
COPY src ./src
RUN yarn prisma generate
RUN yarn build:dev

CMD yarn start:dev
