version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:${POSTGRES_PORT:-5432}'
  bot:
    build:
      context: .
    depends_on:
      - 'postgres'
    environment:
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PORT: ${POSTGRES_PORT:-5432}
