version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: botler-database
    restart: unless-stopped
    ports:
      - '5432:${DATABASE_PORT:-5432}'
  bot:
    build:
      context: .
    depends_on:
      - 'db'
    environment:
      TYPEORM_HOST: botler-database
      TYPEORM_USERNAME: postgres
      TYPEORM_PORT: ${DATABASE_PORT:-5432}
