FROM node:14-alpine AS builder

WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

COPY tsconfig.json ./
COPY src ./src
RUN yarn build:prod

RUN yarn install --production

FROM mhart/alpine-node:slim-14

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Do not use Yarn here because the slim version does not have it installed
CMD ["node","./dist/main.js"]
