note: this kubernetes solution is only designed for a single node cluster

how to use:
  - run "./build-docker.sh" in the root directory
  - run "cd kubernetes/"
  - run "./setup.sh"

directories:
  initialmanifests: resources that dont tend to change often (namespaces, persistent volumes, configmaps)
  manifests: resources that change often (pods, deployments)
